apiVersion: prcontroller.ephemeralenv.io.prcontroller.ephemeralenv.io/v1alpha1
kind: PREphemeralEnvController
metadata:
  name: pr-eph-env-ctrlr-1
spec:
  githubPRRepository:
    user: manisbindra
    repo: ephemeral-app
    tokenSecretRef: 
      name: tokensecret
      namespace: default
      key: token
  envCreationHelmRepo:
    fluxSourceRepoName: infra-repo-public
    helmChartPath: ephemeral-env
    chartVersion: 0.1.0
    destinationNamespace: pr-helm-releases
  interval: "60s"

